### ISSUE TITLE
Stig crashing - installed from master.

### ISSUE THREAD

**Issue by DiagonalArg** [rndusr/stig#105]
Ubuntu 16.04.  Just installed via:

```
pip3 install --user 'git+https://github.com/rndusr/stig.git#egg=stig[geoip,setproctitle]'
```

Crashing:

```
$ stig
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/main.py", line 206, in runurwidloop.run()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 286, in run self._run()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 384, in _run self.event_loop.run()
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/urwidpatches.py", line 175, in run raise self._exc_info
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run self._callback(*self._args)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 77, in reraise task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step result = coro.throw(exc)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 87, in _poll_loop await self._poll_task
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__ yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step result = coro.send(None)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 116, in _do_poll response = await self._request()
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/api_torrent.py", line 374, in torrents return await self._get_torrents_by_ids(keys, from_cache=from_cache) File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/api_torrent.py", line 305, in _get_torrents_by_ids response = await self._request_torrents(fields, ids)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/api_torrent.py", line 224, in _request_torrents raw_tlist = await self.rpc.torrent_get(fields=fields) File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/rpc.py", line 405, in request await self.connect() File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/rpc.py", line 273, in connect import aiohttp
  File "/home/user/.local/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module> from .client import (
  File "/home/user/.local/lib/python3.5/site-packages/aiohttp/client.py", line 12, in <module> from typing import (  # noqa
ImportError: cannot import name 'Coroutine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/stig", line 9, in <module> load_entry_point('stig==0.10.1a0', 'console_scripts', 'stig')()
  File "/home/user/.local/lib/python3.5/site-packages/stig/__init__.py", line 24, in run main.run()
  File "/home/user/.local/lib/python3.5/site-packages/stig/main.py", line 115, in run if not tui.run(run_commands):
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/main.py", line 210, in run aioloop.run_until_complete(srvapi.stop_polling())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step result = coro.send(None)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/api.py", line 206, in stop_polling await poller.stop()
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/api_status.py", line 35, in stop await self._poller_stats.stop(*args, **kwargs) File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 157, in stop await asyncio.wait_for(self._poll_loop_task, timeout=0, loop=self.loop) File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run self._callback(*self._args)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 77, in reraise task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step result = coro.throw(exc)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 87, in _poll_loop await self._poll_task
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__ yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step result = coro.send(None)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 116, in _do_poll response = await self._request()
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/rpc.py", line 405, in request await self.connect()
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/rpc.py", line 273, in connect import aiohttp
  File "/home/user/.local/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module> from .client import (
  File "/home/user/.local/lib/python3.5/site-packages/aiohttp/client.py", line 12, in <module> from typing import (  # noqa
ImportError: cannot import name 'Coroutine'
Exception ignored in: <bound method RequestPoller.__del__ of <SettingsAPI session_get(), callbacks=['SettingsAPI._handle_session_get()'], error_callbacks=['SettingsAPI._handle_error()']>>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 166, in __del__
RuntimeError: You forgot to call stop() on <SettingsAPI session_get(), callbacks=['SettingsAPI._handle_session_get()'], error_callbacks=['SettingsAPI._handle_error()']>
Exception ignored in: <bound method RequestPoller.__del__ of <RequestPoller TorrentAPI.torrents(keys=('rate-down', 'rate-up', 'status')), callbacks=['StatusAPI._handle_torrent_list()'], error_callbacks=[]>>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 166, in __del__
RuntimeError: You forgot to call stop() on <RequestPoller TorrentAPI.torrents(keys=('rate-down', 'rate-up', 'status')), callbacks=['StatusAPI._handle_torrent_list()'], error_callbacks=[]>
Exception ignored in: <bound method RequestPoller.__del__ of <TorrentRequestPool TorrentAPI.torrents(torrents=None, keys={'size-final', 'peers-connected', 'status', 'time-activity', 'size-downloaded', 'trackers', 'path', 'peers-seeding', 'time-completed', 'size-uploaded', 'rate-up', 'timespan-eta', 'name', '%verified', '%downloaded', 'rate-down', 'error', 'ratio', '%metadata'}), callbacks=['TorrentRequestPool._handle_torrent_list()'], error_callbacks=[]>>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 166, in __del__
RuntimeError: You forgot to call stop() on <TorrentRequestPool TorrentAPI.torrents(torrents=None, keys={'size-final', 'peers-connected', 'status', 'time-activity', 'size-downloaded', 'trackers', 'path', 'peers-seeding', 'time-completed', 'size-uploaded', 'rate-up', 'timespan-eta', 'name', '%verified', '%downloaded', 'rate-down', 'error', 'ratio', '%metadata'}), callbacks=['TorrentRequestPool._handle_torrent_list()'], error_callbacks=[]>
Exception ignored in: <bound method RequestPoller.__del__ of <RequestPoller TorrentAPI.torrents(None, keys=('peers', 'name', 'id')), callbacks=['PeerListWidget._handle_peers()'], error_callbacks=[]>>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/poll.py", line 166, in __del__
RuntimeError: You forgot to call stop() on <RequestPoller TorrentAPI.torrents(None, keys=('peers', 'name', 'id')), callbacks=['PeerListWidget._handle_peers()'], error_callbacks=[]>
Task was destroyed but it is pending!
task: <Task pending coro=<API._manage_pollers() running at /home/user/.local/lib/python3.5/site-packages/stig/client/api.py:161> wait_for=<Future pending cb=[Task._wakeup()]> cb=[API.start_polling.<locals>.<lambda>() at /home/user/.local/lib/python3.5/site-packages/stig/client/api.py:200]>ib/pyth!
```

**Comment by rndusr** [comment]
Thanks for your report.
Should be fixed now.

**Comment by DiagonalArg** [comment]
Still failing ...

$ stig
Traceback (most recent call last):
  File "/home/user/.local/bin/stig", line 9, in <module> load_entry_point('stig==0.10.1a0', 'console_scripts', 'stig')()
  File "/home/user/.local/lib/python3.5/site-packages/stig/__init__.py", line 24, in run main.run()
  File "/home/user/.local/lib/python3.5/site-packages/stig/main.py", line 115, in run if not tui.run(run_commands):
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/main.py", line 206, in run urwidloop.run()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 286, in run self._run()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 384, in _run self.event_loop.run()
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/urwidpatches.py", line 175, in run raise self._exc_info
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run self._callback(*self._args)
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/main.py", line 51, in _handle_geoip_load_result task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step result = coro.throw(exc)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/geoip.py", line 87, in load await self._update_dbfile(loop)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/geoip.py", line 110, in _update_dbfile async with session.get(self.url, timeout=self.timeout) as resp: File "/home/user/.local/lib/python3.5/site-packages/aiohttp/client.py", line 855, in __aenter__ self._resp = await self._coro File "/home/user/.local/lib/python3.5/site-packages/aiohttp/client.py", line 469, in _request break
  File "/home/user/.local/lib/python3.5/site-packages/aiohttp/helpers.py", line 673, in __exit__ raise asyncio.TimeoutError from None concurrent.futures._base.TimeoutError

**Comment by rndusr** [comment]
aiohttp depends on Python 3.5.3 or higher and Ubuntu 16.04 seems to ship Python
3.5.1 or 3.5.2. I'm not sure if there's anything I can do.

What puzzles me is that the installation procedure doesn't fail. It should
either complain that the aiohttp version shipped by Ubuntu is too old or that
the aiohttp version from pypi can't be installed because the Python version is
too old.

Can you provide the output of these commands?

    python3 --version
    pip3 show aiohttp

**Comment by rndusr** [comment]
OK, that confirms my confusion. aiohttp should refuse to install because it
needs at least Python 3.5.3.

I'm out of ideas at the moment.

**Comment by DiagonalArg** [comment]
Alright, thanks.  

I wonder if I could do a local install of a newer python, maybe via linuxbrew if nothing else.  I'll look into it and if relevant, report back here.

**Comment by rndusr** [comment]
You can always compile and install from the official sources, but I wouldn't do
that on a system you rely on because it might break system tools who expect a
certain python version.

There is a backports repo for cases like this, but it doesn't seem to have a
newer python version.

The easiest way, if possible, would be to upgrade to the new Ubuntu LTS. But I
can't really offer that as the solution since I try to support Python 3.5.

**Comment by mabushey** [comment]
You could run it in docker. No promises when, but I'm planning on making a simple dockerfile for stig. `docker -rm` is awesome.

**Comment by DiagonalArg** [comment]
@mabushey - thanks.  I really want to start making use of LXC, but just haven't quite gotten there yet ...

**Comment by rndusr** [comment]
Closing this because it looks like an upstream issue.
