### ISSUE TITLE
urwid 2.4.2 and higher break stig

### ISSUE THREAD

**Issue by mfonville** [rndusr/stig#244]
When stig wasn't working with the latest urwid, I tried several versions to pinpoint which had the breaking changes, which is 2.4.2

Trace: 
``
Traceback (most recent call last):
  File "/home/maarten/.local/bin/stig", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/__init__.py", line 25, in run
    main.run()
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/main.py", line 102, in run
    if not tui.run(run_commands):
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/main.py", line 30, in run
    from . import tuiobjects
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/tuiobjects.py", line 107, in <module>
    logwidget = LogWidget(height=int(objects.localcfg['tui.log.height']),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/logger.py", line 45, in __init__
    self._scrollable = Scrollable(self._pile)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/scroll.py", line 46, in __init__
    raise ValueError('Not a fixed or flow widget: %r' % widget)
ValueError: Not a fixed or flow widget: <Pile widget>
``

**Comment by rndusr** [comment]
stig requires urwid 2.2.*. This is specified in setup.py.

As a workaround until stig can adapt to the breaking changes in urwid, try
installing stig with pipx.

**Comment by mfonville** [comment]
I have stig installed with pipx, but because earlier I had hit issue #238 I had explicitly injected a certain version of urwid.
When I ran `pipx upgrade` with `--include-injected` for stig, urwid also got an update and I noticed the incompatibility.

I now removed urwid from the explicit injections and indeed it correctly retains 2.2.* :-)

**Comment by Soundtoxin** [comment]
Ran into this same issue after an Arch update recently. I was using `stig-git` from the AUR previously, so just uninstalled that with `yay -R stig-git` and then installed stig with `pipx install stig` and it seemed to work right away with my same config and launching the tui as usual (in case it helps the next person to come across this problem save a few minutes).

Long live stig!

**Comment by mfonville** [comment]
Great that stig now works with more recent urwid.
If I start stig since the latest release, I get this notification at startup (but stig works fine):
```
/home/maarten/.local/pipx/venvs/stig/lib/python3.12/site-packages/urwid/widget/grid_flow.py:81: GridFlowWarning: Size is smaller than cell width (-1 < 20)
  super().__init__(self.generate_display_widget((self._cache_maxcol,)))
```

**Comment by rndusr** [comment]
Should be fixed in 0.12.10a0.

**Comment by rsekman** [comment]
> Great that stig now works with more recent urwid. If I start stig since the latest release, I get this notification at startup (but stig works fine):
> 
> ```
> /home/maarten/.local/pipx/venvs/stig/lib/python3.12/site-packages/urwid/widget/grid_flow.py:81: GridFlowWarning: Size is smaller than cell width (-1 < 20)
>   super().__init__(self.generate_display_widget((self._cache_maxcol,)))
> ```

This was an upstream issue in urwid, which is fixed as of [urwid 2.6.14](https://github.com/urwid/urwid/releases/tag/2.6.14).

**Comment by blibers** [comment]
> Should be fixed in 0.12.10a0.

I'm on this version (AUR), urwid error still persists

> > Great that stig now works with more recent urwid. If I start stig since the latest release, I get this notification at startup (but stig works fine):
> > ```
> > /home/maarten/.local/pipx/venvs/stig/lib/python3.12/site-packages/urwid/widget/grid_flow.py:81: GridFlowWarning: Size is smaller than cell width (-1 < 20)
> >   super().__init__(self.generate_display_widget((self._cache_maxcol,)))
> > ```
> 
> This was an upstream issue in urwid, which is fixed as of [urwid 2.6.14](https://github.com/urwid/urwid/releases/tag/2.6.14).

Arch still is on version 2.6.10-3 

I've tried installing by using pipx, but it seems that pipx is also broken? it gives me some distutils errors...

**Comment by rndusr** [comment]
AUR seems to have stig 0.12.6a0-1?
https://aur.archlinux.org/packages/stig

For stig 0.12.10a0 you need urwid 2.6.12 or higher.

Sounds like something you should ask the AUR package maintainer about.

If the pipx Arch package is broken, I'd install it with `pip install --user pipx`. It's going to
pollute ~/.local, but if that's the only package you install with pip, it shouldn't be too bad.

**Comment by blibers** [comment]
> AUR seems to have stig 0.12.6a0-1? https://aur.archlinux.org/packages/stig For stig 0.12.10a0 you need urwid 2.6.12 or higher. Sounds like something you should ask the AUR package maintainer about. If the pipx Arch package is broken, I'd install it with `pip install --user pipx`. It's going to pollute ~/.local, but if that's the only package you install with pip, it shouldn't be too bad.

It seems somebody just contacted the AUR package mantainer
If stig requires urwid 2.6.12 higher, than it also needs to be properly packaged on AUR (a -git version)

**Comment by rsekman** [comment]
The Arch `python-urwid` package has been flagged out of date for a long
time; it's on 2.6.10 but we need >=2.6.12. I've put an updated
`PKGBUILD` which you can use to install `python-urwid=2.6.15` here:
https://github.com/rsekman/python-urwid

**Comment by blibers** [comment]
> The Arch `python-urwid` package has been flagged out of date for a long time; it's on 2.6.10 but we need >=2.6.12. I've put an updated `PKGBUILD` which you can use to install `python-urwid=2.6.15` here: https://github.com/rsekman/python-urwid

I'm getting this when compiling your version:
`ModuleNotFoundError: No module named 'distutils'
`
This is the same error I get with pipx. Am I the only one?
I'm no python expert, but as far as I know distutils got deprecated?
Installing python-setuptools package didn't help

**Comment by rsekman** [comment]
That is very strange. On my Arch it builds fine, and the only
significant modification from the official `PKGBUILD` is bumping the
version. If you run `pacman -Ql python-setuptools | grep distutils`,
what does that list?

**Comment by blibers** [comment]
> That is very strange. On my Arch it builds fine, and the only significant modification from the official `PKGBUILD` is bumping the version. If you run `pacman -Ql python-setuptools | grep distutils`, what does that list?

Thanks for your reply!
I get this, it seems all normal I think, distutils is there. Wrong location, maybe? Any clues?

```
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/__init__.py
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/override.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/override.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/_distutils_hack/override.py
python-setuptools /usr/lib/python3.12/site-packages/distutils-precedence.pth
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__init__.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/__init__.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/__init__.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_collections.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_collections.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_functools.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_functools.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_log.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_log.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_macos_compat.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_macos_compat.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_modified.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_modified.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_msvccompiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/_msvccompiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/archive_util.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/archive_util.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/bcppcompiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/bcppcompiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/ccompiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/ccompiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/cmd.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/cmd.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/config.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/config.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/core.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/core.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/cygwinccompiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/cygwinccompiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/debug.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/debug.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/dep_util.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/dep_util.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/dir_util.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/dir_util.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/dist.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/dist.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/errors.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/errors.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/extension.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/extension.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/fancy_getopt.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/fancy_getopt.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/file_util.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/file_util.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/filelist.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/filelist.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/log.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/log.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/msvc9compiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/msvc9compiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/msvccompiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/msvccompiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/py38compat.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/py38compat.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/py39compat.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/py39compat.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/spawn.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/spawn.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/sysconfig.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/sysconfig.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/text_file.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/text_file.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/unixccompiler.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/unixccompiler.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/util.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/util.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/version.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/version.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/versionpredicate.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/__pycache__/versionpredicate.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/_collections.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/_functools.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/_log.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/_macos_compat.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/_modified.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/_msvccompiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/archive_util.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/bcppcompiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__init__.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/__init__.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/__init__.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/_framework_compat.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/_framework_compat.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/bdist.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/bdist.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/bdist_dumb.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/bdist_dumb.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/bdist_rpm.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/bdist_rpm.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_clib.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_clib.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_ext.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_ext.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_py.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_py.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_scripts.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/build_scripts.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/check.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/check.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/clean.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/clean.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/config.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/config.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_data.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_data.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_egg_info.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_egg_info.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_headers.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_headers.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_lib.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_lib.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_scripts.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/install_scripts.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/py37compat.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/py37compat.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/register.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/register.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/sdist.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/sdist.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/upload.cpython-312.opt-1.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/__pycache__/upload.cpython-312.pyc
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/_framework_compat.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/bdist.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/bdist_dumb.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/bdist_rpm.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/build.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_clib.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_py.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_scripts.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/check.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/clean.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/config.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/install.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/install_data.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/install_egg_info.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/install_headers.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/install_lib.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/install_scripts.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/py37compat.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/register.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/command/upload.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/config.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/core.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/cygwinccompiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/debug.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/dep_util.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/dir_util.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/errors.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/extension.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/fancy_getopt.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/file_util.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/filelist.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/log.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/msvc9compiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/msvccompiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/py38compat.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/py39compat.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/spawn.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/sysconfig.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/text_file.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/util.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/version.py
python-setuptools /usr/lib/python3.12/site-packages/setuptools/_distutils/versionpredicate.py
```

**Comment by blibers** [comment]
Oh, ok, my bad, I had a conflict with the thing being located also on ~/.local
After removing it I was able to install your version of python-urwid! 
stig is now fully working! Thanks!
